/* $NetBSD$ */

/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD: syscalls.master,v 1.309 2021/11/01 05:07:17 thorpej Exp
 */

#include <sys/cdefs.h>
__KERNEL_RCSID(0, "$NetBSD$");

#if defined(_KERNEL_OPT)
#ifdef _KERNEL_OPT
#include "opt_modular.h"
#include "opt_ntp.h"
#include "opt_sysv.h"
#endif
#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/socket.h>
#include <sys/mount.h>
#include <sys/sched.h>
#include <sys/idtype.h>
#include <sys/syscallargs.h>
#include <sys/acl.h>
#include <sys/port.h>
#else /* _KERNEL_OPT */
#include <sys/null.h>
#endif /* _KERNEL_OPT */

const char *const syscallnames[] = {
	/*   0 */	"syscall",
	/*   1 */	"exit",
	/*   2 */	"fork",
	/*   3 */	"read",
	/*   4 */	"write",
	/*   5 */	"open",
	/*   6 */	"close",
	/*   7 */	"compat_50_wait4",
	/*   8 */	"compat_43_ocreat",
	/*   9 */	"link",
	/*  10 */	"unlink",
	/*  11 */	"#11 (obsolete execv)",
	/*  12 */	"chdir",
	/*  13 */	"fchdir",
	/*  14 */	"compat_50_mknod",
	/*  15 */	"chmod",
	/*  16 */	"chown",
	/*  17 */	"break",
	/*  18 */	"compat_20_getfsstat",
	/*  19 */	"compat_43_olseek",
	/*  20 */	"getpid",
	/*  21 */	"compat_40_mount",
	/*  22 */	"unmount",
	/*  23 */	"setuid",
	/*  24 */	"getuid",
	/*  25 */	"geteuid",
	/*  26 */	"ptrace",
	/*  27 */	"recvmsg",
	/*  28 */	"sendmsg",
	/*  29 */	"recvfrom",
	/*  30 */	"accept",
	/*  31 */	"getpeername",
	/*  32 */	"getsockname",
	/*  33 */	"access",
	/*  34 */	"chflags",
	/*  35 */	"fchflags",
	/*  36 */	"sync",
	/*  37 */	"kill",
	/*  38 */	"compat_43_stat43",
	/*  39 */	"getppid",
	/*  40 */	"compat_43_lstat43",
	/*  41 */	"dup",
	/*  42 */	"pipe",
	/*  43 */	"getegid",
	/*  44 */	"profil",
	/*  45 */	"ktrace",
	/*  46 */	"compat_13_sigaction13",
	/*  47 */	"getgid",
	/*  48 */	"compat_13_sigprocmask13",
	/*  49 */	"__getlogin",
	/*  50 */	"__setlogin",
	/*  51 */	"acct",
	/*  52 */	"compat_13_sigpending13",
	/*  53 */	"compat_13_sigaltstack13",
	/*  54 */	"ioctl",
	/*  55 */	"compat_12_oreboot",
	/*  56 */	"revoke",
	/*  57 */	"symlink",
	/*  58 */	"readlink",
	/*  59 */	"execve",
	/*  60 */	"umask",
	/*  61 */	"chroot",
	/*  62 */	"compat_43_fstat43",
	/*  63 */	"compat_43_ogetkerninfo",
	/*  64 */	"compat_43_ogetpagesize",
	/*  65 */	"compat_12_msync",
	/*  66 */	"vfork",
	/*  67 */	"#67 (obsolete vread)",
	/*  68 */	"#68 (obsolete vwrite)",
	/*  69 */	"#69 (obsolete sbrk)",
	/*  70 */	"#70 (obsolete sstk)",
	/*  71 */	"compat_43_ommap",
	/*  72 */	"vadvise",
	/*  73 */	"munmap",
	/*  74 */	"mprotect",
	/*  75 */	"madvise",
	/*  76 */	"#76 (obsolete vhangup)",
	/*  77 */	"#77 (obsolete vlimit)",
	/*  78 */	"mincore",
	/*  79 */	"getgroups",
	/*  80 */	"setgroups",
	/*  81 */	"getpgrp",
	/*  82 */	"setpgid",
	/*  83 */	"compat_50_setitimer",
	/*  84 */	"compat_43_owait",
	/*  85 */	"compat_12_oswapon",
	/*  86 */	"compat_50_getitimer",
	/*  87 */	"compat_43_ogethostname",
	/*  88 */	"compat_43_osethostname",
	/*  89 */	"compat_43_ogetdtablesize",
	/*  90 */	"dup2",
	/*  91 */	"getrandom",
	/*  92 */	"fcntl",
	/*  93 */	"compat_50_select",
	/*  94 */	"#94 (unimplemented setdopt)",
	/*  95 */	"fsync",
	/*  96 */	"setpriority",
	/*  97 */	"compat_30_socket",
	/*  98 */	"connect",
	/*  99 */	"compat_43_oaccept",
	/* 100 */	"getpriority",
	/* 101 */	"compat_43_osend",
	/* 102 */	"compat_43_orecv",
	/* 103 */	"compat_13_sigreturn13",
	/* 104 */	"bind",
	/* 105 */	"setsockopt",
	/* 106 */	"listen",
	/* 107 */	"#107 (obsolete vtimes)",
	/* 108 */	"compat_43_osigvec",
	/* 109 */	"compat_43_osigblock",
	/* 110 */	"compat_43_osigsetmask",
	/* 111 */	"compat_13_sigsuspend13",
	/* 112 */	"compat_43_osigstack",
	/* 113 */	"compat_43_orecvmsg",
	/* 114 */	"compat_43_osendmsg",
	/* 115 */	"#115 (obsolete vtrace)",
	/* 116 */	"compat_50_gettimeofday",
	/* 117 */	"compat_50_getrusage",
	/* 118 */	"getsockopt",
	/* 119 */	"#119 (obsolete resuba)",
	/* 120 */	"readv",
	/* 121 */	"writev",
	/* 122 */	"compat_50_settimeofday",
	/* 123 */	"fchown",
	/* 124 */	"fchmod",
	/* 125 */	"compat_43_orecvfrom",
	/* 126 */	"setreuid",
	/* 127 */	"setregid",
	/* 128 */	"rename",
	/* 129 */	"compat_43_otruncate",
	/* 130 */	"compat_43_oftruncate",
	/* 131 */	"flock",
	/* 132 */	"mkfifo",
	/* 133 */	"sendto",
	/* 134 */	"shutdown",
	/* 135 */	"socketpair",
	/* 136 */	"mkdir",
	/* 137 */	"rmdir",
	/* 138 */	"compat_50_utimes",
	/* 139 */	"#139 (obsolete 4.2 sigreturn)",
	/* 140 */	"compat_50_adjtime",
	/* 141 */	"compat_43_ogetpeername",
	/* 142 */	"compat_43_ogethostid",
	/* 143 */	"compat_43_osethostid",
	/* 144 */	"compat_43_ogetrlimit",
	/* 145 */	"compat_43_osetrlimit",
	/* 146 */	"compat_43_okillpg",
	/* 147 */	"setsid",
	/* 148 */	"compat_50_quotactl",
	/* 149 */	"compat_43_oquota",
	/* 150 */	"compat_43_ogetsockname",
	/* 151 */	"#151 (unimplemented)",
	/* 152 */	"#152 (unimplemented)",
	/* 153 */	"#153 (unimplemented)",
	/* 154 */	"#154 (unimplemented)",
	/* 155 */	"nfssvc",
	/* 156 */	"compat_43_ogetdirentries",
	/* 157 */	"compat_20_statfs",
	/* 158 */	"compat_20_fstatfs",
	/* 159 */	"#159 (unimplemented)",
	/* 160 */	"#160 (unimplemented)",
	/* 161 */	"compat_30_getfh",
	/* 162 */	"compat_09_ogetdomainname",
	/* 163 */	"compat_09_osetdomainname",
	/* 164 */	"compat_09_ouname",
	/* 165 */	"sysarch",
	/* 166 */	"__futex",
	/* 167 */	"__futex_set_robust_list",
	/* 168 */	"__futex_get_robust_list",
#if !defined(_LP64)
	/* 169 */	"compat_10_osemsys",
#else
	/* 169 */	"#169 (excluded 1.0 semsys)",
#endif
#if !defined(_LP64)
	/* 170 */	"compat_10_omsgsys",
#else
	/* 170 */	"#170 (excluded 1.0 msgsys)",
#endif
#if !defined(_LP64)
	/* 171 */	"compat_10_oshmsys",
#else
	/* 171 */	"#171 (excluded 1.0 shmsys)",
#endif
	/* 172 */	"#172 (unimplemented)",
	/* 173 */	"pread",
	/* 174 */	"pwrite",
	/* 175 */	"compat_30_ntp_gettime",
#if defined(NTP) || !defined(_KERNEL_OPT)
	/* 176 */	"ntp_adjtime",
#else
	/* 176 */	"#176 (excluded ntp_adjtime)",
#endif
	/* 177 */	"timerfd_create",
	/* 178 */	"timerfd_settime",
	/* 179 */	"timerfd_gettime",
	/* 180 */	"#180 (unimplemented)",
	/* 181 */	"setgid",
	/* 182 */	"setegid",
	/* 183 */	"seteuid",
	/* 184 */	"lfs_bmapv",
	/* 185 */	"lfs_markv",
	/* 186 */	"lfs_segclean",
	/* 187 */	"compat_50_lfs_segwait",
	/* 188 */	"compat_12_stat12",
	/* 189 */	"compat_12_fstat12",
	/* 190 */	"compat_12_lstat12",
	/* 191 */	"pathconf",
	/* 192 */	"fpathconf",
	/* 193 */	"getsockopt2",
	/* 194 */	"getrlimit",
	/* 195 */	"setrlimit",
	/* 196 */	"compat_12_getdirentries",
	/* 197 */	"mmap",
	/* 198 */	"__syscall",
	/* 199 */	"lseek",
	/* 200 */	"truncate",
	/* 201 */	"ftruncate",
	/* 202 */	"__sysctl",
	/* 203 */	"mlock",
	/* 204 */	"munlock",
	/* 205 */	"undelete",
	/* 206 */	"compat_50_futimes",
	/* 207 */	"getpgid",
	/* 208 */	"reboot",
	/* 209 */	"poll",
	/* 210 */	"afssys",
	/* 211 */	"#211 (unimplemented)",
	/* 212 */	"#212 (unimplemented)",
	/* 213 */	"#213 (unimplemented)",
	/* 214 */	"#214 (unimplemented)",
	/* 215 */	"#215 (unimplemented)",
	/* 216 */	"#216 (unimplemented)",
	/* 217 */	"#217 (unimplemented)",
	/* 218 */	"#218 (unimplemented)",
	/* 219 */	"#219 (unimplemented)",
	/* 220 */	"compat_14___semctl",
	/* 221 */	"semget",
	/* 222 */	"semop",
	/* 223 */	"semconfig",
	/* 224 */	"compat_14_msgctl",
	/* 225 */	"msgget",
	/* 226 */	"msgsnd",
	/* 227 */	"msgrcv",
	/* 228 */	"shmat",
	/* 229 */	"compat_14_shmctl",
	/* 230 */	"shmdt",
	/* 231 */	"shmget",
	/* 232 */	"compat_50_clock_gettime",
	/* 233 */	"compat_50_clock_settime",
	/* 234 */	"compat_50_clock_getres",
	/* 235 */	"timer_create",
	/* 236 */	"timer_delete",
	/* 237 */	"compat_50_timer_settime",
	/* 238 */	"compat_50_timer_gettime",
	/* 239 */	"timer_getoverrun",
	/* 240 */	"compat_50_nanosleep",
	/* 241 */	"fdatasync",
	/* 242 */	"mlockall",
	/* 243 */	"munlockall",
	/* 244 */	"compat_50___sigtimedwait",
	/* 245 */	"sigqueueinfo",
	/* 246 */	"modctl",
	/* 247 */	"_ksem_init",
	/* 248 */	"_ksem_open",
	/* 249 */	"_ksem_unlink",
	/* 250 */	"_ksem_close",
	/* 251 */	"_ksem_post",
	/* 252 */	"_ksem_wait",
	/* 253 */	"_ksem_trywait",
	/* 254 */	"_ksem_getvalue",
	/* 255 */	"_ksem_destroy",
	/* 256 */	"_ksem_timedwait",
	/* 257 */	"mq_open",
	/* 258 */	"mq_close",
	/* 259 */	"mq_unlink",
	/* 260 */	"mq_getattr",
	/* 261 */	"mq_setattr",
	/* 262 */	"mq_notify",
	/* 263 */	"mq_send",
	/* 264 */	"mq_receive",
	/* 265 */	"compat_50_mq_timedsend",
	/* 266 */	"compat_50_mq_timedreceive",
	/* 267 */	"eventfd",
	/* 268 */	"#268 (unimplemented)",
	/* 269 */	"#269 (unimplemented)",
	/* 270 */	"__posix_rename",
	/* 271 */	"swapctl",
	/* 272 */	"compat_30_getdents",
	/* 273 */	"minherit",
	/* 274 */	"lchmod",
	/* 275 */	"lchown",
	/* 276 */	"compat_50_lutimes",
	/* 277 */	"__msync13",
	/* 278 */	"compat_30___stat13",
	/* 279 */	"compat_30___fstat13",
	/* 280 */	"compat_30___lstat13",
	/* 281 */	"__sigaltstack14",
	/* 282 */	"__vfork14",
	/* 283 */	"__posix_chown",
	/* 284 */	"__posix_fchown",
	/* 285 */	"__posix_lchown",
	/* 286 */	"getsid",
	/* 287 */	"__clone",
	/* 288 */	"fktrace",
	/* 289 */	"preadv",
	/* 290 */	"pwritev",
	/* 291 */	"compat_16___sigaction14",
	/* 292 */	"__sigpending14",
	/* 293 */	"__sigprocmask14",
	/* 294 */	"__sigsuspend14",
	/* 295 */	"compat_16___sigreturn14",
	/* 296 */	"__getcwd",
	/* 297 */	"fchroot",
	/* 298 */	"compat_30_fhopen",
	/* 299 */	"compat_30_fhstat",
	/* 300 */	"compat_20_fhstatfs",
	/* 301 */	"compat_50_____semctl13",
	/* 302 */	"compat_50___msgctl13",
	/* 303 */	"compat_50___shmctl13",
	/* 304 */	"lchflags",
	/* 305 */	"issetugid",
	/* 306 */	"utrace",
	/* 307 */	"getcontext",
	/* 308 */	"setcontext",
	/* 309 */	"_lwp_create",
	/* 310 */	"_lwp_exit",
	/* 311 */	"_lwp_self",
	/* 312 */	"_lwp_wait",
	/* 313 */	"_lwp_suspend",
	/* 314 */	"_lwp_continue",
	/* 315 */	"_lwp_wakeup",
	/* 316 */	"_lwp_getprivate",
	/* 317 */	"_lwp_setprivate",
	/* 318 */	"_lwp_kill",
	/* 319 */	"_lwp_detach",
	/* 320 */	"compat_50__lwp_park",
	/* 321 */	"_lwp_unpark",
	/* 322 */	"_lwp_unpark_all",
	/* 323 */	"_lwp_setname",
	/* 324 */	"_lwp_getname",
	/* 325 */	"_lwp_ctl",
	/* 326 */	"#326 (unimplemented)",
	/* 327 */	"#327 (unimplemented)",
	/* 328 */	"#328 (unimplemented)",
	/* 329 */	"#329 (unimplemented)",
	/* 330 */	"compat_60_sa_register",
	/* 331 */	"compat_60_sa_stacks",
	/* 332 */	"compat_60_sa_enable",
	/* 333 */	"compat_60_sa_setconcurrency",
	/* 334 */	"compat_60_sa_yield",
	/* 335 */	"compat_60_sa_preempt",
	/* 336 */	"#336 (obsolete sys_sa_unblockyield)",
	/* 337 */	"#337 (unimplemented)",
	/* 338 */	"#338 (unimplemented)",
	/* 339 */	"#339 (unimplemented)",
	/* 340 */	"__sigaction_sigtramp",
	/* 341 */	"#341 (obsolete sys_pmc_get_info)",
	/* 342 */	"#342 (obsolete sys_pmc_control)",
	/* 343 */	"rasctl",
	/* 344 */	"kqueue",
	/* 345 */	"compat_50_kevent",
	/* 346 */	"_sched_setparam",
	/* 347 */	"_sched_getparam",
	/* 348 */	"_sched_setaffinity",
	/* 349 */	"_sched_getaffinity",
	/* 350 */	"sched_yield",
	/* 351 */	"_sched_protect",
	/* 352 */	"#352 (unimplemented)",
	/* 353 */	"#353 (unimplemented)",
	/* 354 */	"fsync_range",
	/* 355 */	"uuidgen",
	/* 356 */	"compat_90_getvfsstat",
	/* 357 */	"compat_90_statvfs1",
	/* 358 */	"compat_90_fstatvfs1",
	/* 359 */	"compat_30_fhstatvfs1",
	/* 360 */	"extattrctl",
	/* 361 */	"extattr_set_file",
	/* 362 */	"extattr_get_file",
	/* 363 */	"extattr_delete_file",
	/* 364 */	"extattr_set_fd",
	/* 365 */	"extattr_get_fd",
	/* 366 */	"extattr_delete_fd",
	/* 367 */	"extattr_set_link",
	/* 368 */	"extattr_get_link",
	/* 369 */	"extattr_delete_link",
	/* 370 */	"extattr_list_fd",
	/* 371 */	"extattr_list_file",
	/* 372 */	"extattr_list_link",
	/* 373 */	"compat_50_pselect",
	/* 374 */	"compat_50_pollts",
	/* 375 */	"setxattr",
	/* 376 */	"lsetxattr",
	/* 377 */	"fsetxattr",
	/* 378 */	"getxattr",
	/* 379 */	"lgetxattr",
	/* 380 */	"fgetxattr",
	/* 381 */	"listxattr",
	/* 382 */	"llistxattr",
	/* 383 */	"flistxattr",
	/* 384 */	"removexattr",
	/* 385 */	"lremovexattr",
	/* 386 */	"fremovexattr",
	/* 387 */	"compat_50___stat30",
	/* 388 */	"compat_50___fstat30",
	/* 389 */	"compat_50___lstat30",
	/* 390 */	"__getdents30",
	/* 391 */	"#391 (ignored old posix_fadvise)",
	/* 392 */	"compat_30___fhstat30",
	/* 393 */	"compat_50___ntp_gettime30",
	/* 394 */	"__socket30",
	/* 395 */	"__getfh30",
	/* 396 */	"__fhopen40",
	/* 397 */	"compat_90_fhstatvfs1",
	/* 398 */	"compat_50___fhstat40",
	/* 399 */	"aio_cancel",
	/* 400 */	"aio_error",
	/* 401 */	"aio_fsync",
	/* 402 */	"aio_read",
	/* 403 */	"aio_return",
	/* 404 */	"compat_50_aio_suspend",
	/* 405 */	"aio_write",
	/* 406 */	"lio_listio",
	/* 407 */	"#407 (unimplemented)",
	/* 408 */	"#408 (unimplemented)",
	/* 409 */	"#409 (unimplemented)",
	/* 410 */	"__mount50",
	/* 411 */	"mremap",
	/* 412 */	"pset_create",
	/* 413 */	"pset_destroy",
	/* 414 */	"pset_assign",
	/* 415 */	"_pset_bind",
	/* 416 */	"__posix_fadvise50",
	/* 417 */	"__select50",
	/* 418 */	"__gettimeofday50",
	/* 419 */	"__settimeofday50",
	/* 420 */	"__utimes50",
	/* 421 */	"__adjtime50",
	/* 422 */	"__lfs_segwait50",
	/* 423 */	"__futimes50",
	/* 424 */	"__lutimes50",
	/* 425 */	"__setitimer50",
	/* 426 */	"__getitimer50",
	/* 427 */	"__clock_gettime50",
	/* 428 */	"__clock_settime50",
	/* 429 */	"__clock_getres50",
	/* 430 */	"__nanosleep50",
	/* 431 */	"____sigtimedwait50",
	/* 432 */	"__mq_timedsend50",
	/* 433 */	"__mq_timedreceive50",
	/* 434 */	"compat_60__lwp_park",
	/* 435 */	"__kevent50",
	/* 436 */	"__pselect50",
	/* 437 */	"__pollts50",
	/* 438 */	"__aio_suspend50",
	/* 439 */	"__stat50",
	/* 440 */	"__fstat50",
	/* 441 */	"__lstat50",
	/* 442 */	"____semctl50",
	/* 443 */	"__shmctl50",
	/* 444 */	"__msgctl50",
	/* 445 */	"__getrusage50",
	/* 446 */	"__timer_settime50",
	/* 447 */	"__timer_gettime50",
#if defined(NTP) || !defined(_KERNEL_OPT)
	/* 448 */	"__ntp_gettime50",
#else
	/* 448 */	"#448 (excluded ___ntp_gettime50)",
#endif
	/* 449 */	"__wait450",
	/* 450 */	"__mknod50",
	/* 451 */	"__fhstat50",
	/* 452 */	"#452 (obsolete 5.99 quotactl)",
	/* 453 */	"pipe2",
	/* 454 */	"dup3",
	/* 455 */	"kqueue1",
	/* 456 */	"paccept",
	/* 457 */	"linkat",
	/* 458 */	"renameat",
	/* 459 */	"mkfifoat",
	/* 460 */	"mknodat",
	/* 461 */	"mkdirat",
	/* 462 */	"faccessat",
	/* 463 */	"fchmodat",
	/* 464 */	"fchownat",
	/* 465 */	"fexecve",
	/* 466 */	"fstatat",
	/* 467 */	"utimensat",
	/* 468 */	"openat",
	/* 469 */	"readlinkat",
	/* 470 */	"symlinkat",
	/* 471 */	"unlinkat",
	/* 472 */	"futimens",
	/* 473 */	"__quotactl",
	/* 474 */	"posix_spawn",
	/* 475 */	"recvmmsg",
	/* 476 */	"sendmmsg",
	/* 477 */	"clock_nanosleep",
	/* 478 */	"___lwp_park60",
	/* 479 */	"posix_fallocate",
	/* 480 */	"fdiscard",
	/* 481 */	"wait6",
	/* 482 */	"clock_getcpuclockid2",
	/* 483 */	"__getvfsstat90",
	/* 484 */	"__statvfs190",
	/* 485 */	"__fstatvfs190",
	/* 486 */	"__fhstatvfs190",
	/* 487 */	"__acl_get_link",
	/* 488 */	"__acl_set_link",
	/* 489 */	"__acl_delete_link",
	/* 490 */	"__acl_aclcheck_link",
	/* 491 */	"__acl_get_file",
	/* 492 */	"__acl_set_file",
	/* 493 */	"__acl_get_fd",
	/* 494 */	"__acl_set_fd",
	/* 495 */	"__acl_delete_file",
	/* 496 */	"__acl_delete_fd",
	/* 497 */	"__acl_aclcheck_file",
	/* 498 */	"__acl_aclcheck_fd",
	/* 499 */	"lpathconf",
	/* 500 */	"_create_port",
	/* 501 */	"_close_port",
	/* 502 */	"_delete_port",
	/* 503 */	"_find_port",
	/* 504 */	"_get_port_info",
	/* 505 */	"_get_next_port_info",
	/* 506 */	"_port_buffer_size",
	/* 507 */	"_port_buffer_size_etc",
	/* 508 */	"_port_count",
	/* 509 */	"_read_port",
	/* 510 */	"_read_port_etc",
	/* 511 */	"_set_port_owner",
	/* 512 */	"_write_port",
	/* 513 */	"_write_port_etc",
	/* 514 */	"_create_sem",
	/* 515 */	"_delete_sem",
	/* 516 */	"_acquire_sem",
	/* 517 */	"_acquire_sem_etc",
	/* 518 */	"_release_sem",
	/* 519 */	"_release_sem_etc",
	/* 520 */	"_get_sem_count",
	/* 521 */	"_set_sem_owner",
	/* 522 */	"_get_sem_info",
	/* 523 */	"_get_next_sem_info",
	/* 524 */	"_create_area",
	/* 525 */	"_clone_area",
	/* 526 */	"_find_area",
	/* 527 */	"_area_for",
	/* 528 */	"_delete_area",
	/* 529 */	"_resize_area",
	/* 530 */	"_set_area_protection",
	/* 531 */	"_get_area_info",
	/* 532 */	"_get_next_area_info",
	/* 533 */	"# filler",
	/* 534 */	"# filler",
	/* 535 */	"# filler",
	/* 536 */	"# filler",
	/* 537 */	"# filler",
	/* 538 */	"# filler",
	/* 539 */	"# filler",
	/* 540 */	"# filler",
	/* 541 */	"# filler",
	/* 542 */	"# filler",
	/* 543 */	"# filler",
	/* 544 */	"# filler",
	/* 545 */	"# filler",
	/* 546 */	"# filler",
	/* 547 */	"# filler",
	/* 548 */	"# filler",
	/* 549 */	"# filler",
	/* 550 */	"# filler",
	/* 551 */	"# filler",
	/* 552 */	"# filler",
	/* 553 */	"# filler",
	/* 554 */	"# filler",
	/* 555 */	"# filler",
	/* 556 */	"# filler",
	/* 557 */	"# filler",
	/* 558 */	"# filler",
	/* 559 */	"# filler",
	/* 560 */	"# filler",
	/* 561 */	"# filler",
	/* 562 */	"# filler",
	/* 563 */	"# filler",
	/* 564 */	"# filler",
	/* 565 */	"# filler",
	/* 566 */	"# filler",
	/* 567 */	"# filler",
	/* 568 */	"# filler",
	/* 569 */	"# filler",
	/* 570 */	"# filler",
	/* 571 */	"# filler",
	/* 572 */	"# filler",
	/* 573 */	"# filler",
	/* 574 */	"# filler",
	/* 575 */	"# filler",
	/* 576 */	"# filler",
	/* 577 */	"# filler",
	/* 578 */	"# filler",
	/* 579 */	"# filler",
	/* 580 */	"# filler",
	/* 581 */	"# filler",
	/* 582 */	"# filler",
	/* 583 */	"# filler",
	/* 584 */	"# filler",
	/* 585 */	"# filler",
	/* 586 */	"# filler",
	/* 587 */	"# filler",
	/* 588 */	"# filler",
	/* 589 */	"# filler",
	/* 590 */	"# filler",
	/* 591 */	"# filler",
	/* 592 */	"# filler",
	/* 593 */	"# filler",
	/* 594 */	"# filler",
	/* 595 */	"# filler",
	/* 596 */	"# filler",
	/* 597 */	"# filler",
	/* 598 */	"# filler",
	/* 599 */	"# filler",
	/* 600 */	"# filler",
	/* 601 */	"# filler",
	/* 602 */	"# filler",
	/* 603 */	"# filler",
	/* 604 */	"# filler",
	/* 605 */	"# filler",
	/* 606 */	"# filler",
	/* 607 */	"# filler",
	/* 608 */	"# filler",
	/* 609 */	"# filler",
	/* 610 */	"# filler",
	/* 611 */	"# filler",
	/* 612 */	"# filler",
	/* 613 */	"# filler",
	/* 614 */	"# filler",
	/* 615 */	"# filler",
	/* 616 */	"# filler",
	/* 617 */	"# filler",
	/* 618 */	"# filler",
	/* 619 */	"# filler",
	/* 620 */	"# filler",
	/* 621 */	"# filler",
	/* 622 */	"# filler",
	/* 623 */	"# filler",
	/* 624 */	"# filler",
	/* 625 */	"# filler",
	/* 626 */	"# filler",
	/* 627 */	"# filler",
	/* 628 */	"# filler",
	/* 629 */	"# filler",
	/* 630 */	"# filler",
	/* 631 */	"# filler",
	/* 632 */	"# filler",
	/* 633 */	"# filler",
	/* 634 */	"# filler",
	/* 635 */	"# filler",
	/* 636 */	"# filler",
	/* 637 */	"# filler",
	/* 638 */	"# filler",
	/* 639 */	"# filler",
	/* 640 */	"# filler",
	/* 641 */	"# filler",
	/* 642 */	"# filler",
	/* 643 */	"# filler",
	/* 644 */	"# filler",
	/* 645 */	"# filler",
	/* 646 */	"# filler",
	/* 647 */	"# filler",
	/* 648 */	"# filler",
	/* 649 */	"# filler",
	/* 650 */	"# filler",
	/* 651 */	"# filler",
	/* 652 */	"# filler",
	/* 653 */	"# filler",
	/* 654 */	"# filler",
	/* 655 */	"# filler",
	/* 656 */	"# filler",
	/* 657 */	"# filler",
	/* 658 */	"# filler",
	/* 659 */	"# filler",
	/* 660 */	"# filler",
	/* 661 */	"# filler",
	/* 662 */	"# filler",
	/* 663 */	"# filler",
	/* 664 */	"# filler",
	/* 665 */	"# filler",
	/* 666 */	"# filler",
	/* 667 */	"# filler",
	/* 668 */	"# filler",
	/* 669 */	"# filler",
	/* 670 */	"# filler",
	/* 671 */	"# filler",
	/* 672 */	"# filler",
	/* 673 */	"# filler",
	/* 674 */	"# filler",
	/* 675 */	"# filler",
	/* 676 */	"# filler",
	/* 677 */	"# filler",
	/* 678 */	"# filler",
	/* 679 */	"# filler",
	/* 680 */	"# filler",
	/* 681 */	"# filler",
	/* 682 */	"# filler",
	/* 683 */	"# filler",
	/* 684 */	"# filler",
	/* 685 */	"# filler",
	/* 686 */	"# filler",
	/* 687 */	"# filler",
	/* 688 */	"# filler",
	/* 689 */	"# filler",
	/* 690 */	"# filler",
	/* 691 */	"# filler",
	/* 692 */	"# filler",
	/* 693 */	"# filler",
	/* 694 */	"# filler",
	/* 695 */	"# filler",
	/* 696 */	"# filler",
	/* 697 */	"# filler",
	/* 698 */	"# filler",
	/* 699 */	"# filler",
	/* 700 */	"# filler",
	/* 701 */	"# filler",
	/* 702 */	"# filler",
	/* 703 */	"# filler",
	/* 704 */	"# filler",
	/* 705 */	"# filler",
	/* 706 */	"# filler",
	/* 707 */	"# filler",
	/* 708 */	"# filler",
	/* 709 */	"# filler",
	/* 710 */	"# filler",
	/* 711 */	"# filler",
	/* 712 */	"# filler",
	/* 713 */	"# filler",
	/* 714 */	"# filler",
	/* 715 */	"# filler",
	/* 716 */	"# filler",
	/* 717 */	"# filler",
	/* 718 */	"# filler",
	/* 719 */	"# filler",
	/* 720 */	"# filler",
	/* 721 */	"# filler",
	/* 722 */	"# filler",
	/* 723 */	"# filler",
	/* 724 */	"# filler",
	/* 725 */	"# filler",
	/* 726 */	"# filler",
	/* 727 */	"# filler",
	/* 728 */	"# filler",
	/* 729 */	"# filler",
	/* 730 */	"# filler",
	/* 731 */	"# filler",
	/* 732 */	"# filler",
	/* 733 */	"# filler",
	/* 734 */	"# filler",
	/* 735 */	"# filler",
	/* 736 */	"# filler",
	/* 737 */	"# filler",
	/* 738 */	"# filler",
	/* 739 */	"# filler",
	/* 740 */	"# filler",
	/* 741 */	"# filler",
	/* 742 */	"# filler",
	/* 743 */	"# filler",
	/* 744 */	"# filler",
	/* 745 */	"# filler",
	/* 746 */	"# filler",
	/* 747 */	"# filler",
	/* 748 */	"# filler",
	/* 749 */	"# filler",
	/* 750 */	"# filler",
	/* 751 */	"# filler",
	/* 752 */	"# filler",
	/* 753 */	"# filler",
	/* 754 */	"# filler",
	/* 755 */	"# filler",
	/* 756 */	"# filler",
	/* 757 */	"# filler",
	/* 758 */	"# filler",
	/* 759 */	"# filler",
	/* 760 */	"# filler",
	/* 761 */	"# filler",
	/* 762 */	"# filler",
	/* 763 */	"# filler",
	/* 764 */	"# filler",
	/* 765 */	"# filler",
	/* 766 */	"# filler",
	/* 767 */	"# filler",
	/* 768 */	"# filler",
	/* 769 */	"# filler",
	/* 770 */	"# filler",
	/* 771 */	"# filler",
	/* 772 */	"# filler",
	/* 773 */	"# filler",
	/* 774 */	"# filler",
	/* 775 */	"# filler",
	/* 776 */	"# filler",
	/* 777 */	"# filler",
	/* 778 */	"# filler",
	/* 779 */	"# filler",
	/* 780 */	"# filler",
	/* 781 */	"# filler",
	/* 782 */	"# filler",
	/* 783 */	"# filler",
	/* 784 */	"# filler",
	/* 785 */	"# filler",
	/* 786 */	"# filler",
	/* 787 */	"# filler",
	/* 788 */	"# filler",
	/* 789 */	"# filler",
	/* 790 */	"# filler",
	/* 791 */	"# filler",
	/* 792 */	"# filler",
	/* 793 */	"# filler",
	/* 794 */	"# filler",
	/* 795 */	"# filler",
	/* 796 */	"# filler",
	/* 797 */	"# filler",
	/* 798 */	"# filler",
	/* 799 */	"# filler",
	/* 800 */	"# filler",
	/* 801 */	"# filler",
	/* 802 */	"# filler",
	/* 803 */	"# filler",
	/* 804 */	"# filler",
	/* 805 */	"# filler",
	/* 806 */	"# filler",
	/* 807 */	"# filler",
	/* 808 */	"# filler",
	/* 809 */	"# filler",
	/* 810 */	"# filler",
	/* 811 */	"# filler",
	/* 812 */	"# filler",
	/* 813 */	"# filler",
	/* 814 */	"# filler",
	/* 815 */	"# filler",
	/* 816 */	"# filler",
	/* 817 */	"# filler",
	/* 818 */	"# filler",
	/* 819 */	"# filler",
	/* 820 */	"# filler",
	/* 821 */	"# filler",
	/* 822 */	"# filler",
	/* 823 */	"# filler",
	/* 824 */	"# filler",
	/* 825 */	"# filler",
	/* 826 */	"# filler",
	/* 827 */	"# filler",
	/* 828 */	"# filler",
	/* 829 */	"# filler",
	/* 830 */	"# filler",
	/* 831 */	"# filler",
	/* 832 */	"# filler",
	/* 833 */	"# filler",
	/* 834 */	"# filler",
	/* 835 */	"# filler",
	/* 836 */	"# filler",
	/* 837 */	"# filler",
	/* 838 */	"# filler",
	/* 839 */	"# filler",
	/* 840 */	"# filler",
	/* 841 */	"# filler",
	/* 842 */	"# filler",
	/* 843 */	"# filler",
	/* 844 */	"# filler",
	/* 845 */	"# filler",
	/* 846 */	"# filler",
	/* 847 */	"# filler",
	/* 848 */	"# filler",
	/* 849 */	"# filler",
	/* 850 */	"# filler",
	/* 851 */	"# filler",
	/* 852 */	"# filler",
	/* 853 */	"# filler",
	/* 854 */	"# filler",
	/* 855 */	"# filler",
	/* 856 */	"# filler",
	/* 857 */	"# filler",
	/* 858 */	"# filler",
	/* 859 */	"# filler",
	/* 860 */	"# filler",
	/* 861 */	"# filler",
	/* 862 */	"# filler",
	/* 863 */	"# filler",
	/* 864 */	"# filler",
	/* 865 */	"# filler",
	/* 866 */	"# filler",
	/* 867 */	"# filler",
	/* 868 */	"# filler",
	/* 869 */	"# filler",
	/* 870 */	"# filler",
	/* 871 */	"# filler",
	/* 872 */	"# filler",
	/* 873 */	"# filler",
	/* 874 */	"# filler",
	/* 875 */	"# filler",
	/* 876 */	"# filler",
	/* 877 */	"# filler",
	/* 878 */	"# filler",
	/* 879 */	"# filler",
	/* 880 */	"# filler",
	/* 881 */	"# filler",
	/* 882 */	"# filler",
	/* 883 */	"# filler",
	/* 884 */	"# filler",
	/* 885 */	"# filler",
	/* 886 */	"# filler",
	/* 887 */	"# filler",
	/* 888 */	"# filler",
	/* 889 */	"# filler",
	/* 890 */	"# filler",
	/* 891 */	"# filler",
	/* 892 */	"# filler",
	/* 893 */	"# filler",
	/* 894 */	"# filler",
	/* 895 */	"# filler",
	/* 896 */	"# filler",
	/* 897 */	"# filler",
	/* 898 */	"# filler",
	/* 899 */	"# filler",
	/* 900 */	"# filler",
	/* 901 */	"# filler",
	/* 902 */	"# filler",
	/* 903 */	"# filler",
	/* 904 */	"# filler",
	/* 905 */	"# filler",
	/* 906 */	"# filler",
	/* 907 */	"# filler",
	/* 908 */	"# filler",
	/* 909 */	"# filler",
	/* 910 */	"# filler",
	/* 911 */	"# filler",
	/* 912 */	"# filler",
	/* 913 */	"# filler",
	/* 914 */	"# filler",
	/* 915 */	"# filler",
	/* 916 */	"# filler",
	/* 917 */	"# filler",
	/* 918 */	"# filler",
	/* 919 */	"# filler",
	/* 920 */	"# filler",
	/* 921 */	"# filler",
	/* 922 */	"# filler",
	/* 923 */	"# filler",
	/* 924 */	"# filler",
	/* 925 */	"# filler",
	/* 926 */	"# filler",
	/* 927 */	"# filler",
	/* 928 */	"# filler",
	/* 929 */	"# filler",
	/* 930 */	"# filler",
	/* 931 */	"# filler",
	/* 932 */	"# filler",
	/* 933 */	"# filler",
	/* 934 */	"# filler",
	/* 935 */	"# filler",
	/* 936 */	"# filler",
	/* 937 */	"# filler",
	/* 938 */	"# filler",
	/* 939 */	"# filler",
	/* 940 */	"# filler",
	/* 941 */	"# filler",
	/* 942 */	"# filler",
	/* 943 */	"# filler",
	/* 944 */	"# filler",
	/* 945 */	"# filler",
	/* 946 */	"# filler",
	/* 947 */	"# filler",
	/* 948 */	"# filler",
	/* 949 */	"# filler",
	/* 950 */	"# filler",
	/* 951 */	"# filler",
	/* 952 */	"# filler",
	/* 953 */	"# filler",
	/* 954 */	"# filler",
	/* 955 */	"# filler",
	/* 956 */	"# filler",
	/* 957 */	"# filler",
	/* 958 */	"# filler",
	/* 959 */	"# filler",
	/* 960 */	"# filler",
	/* 961 */	"# filler",
	/* 962 */	"# filler",
	/* 963 */	"# filler",
	/* 964 */	"# filler",
	/* 965 */	"# filler",
	/* 966 */	"# filler",
	/* 967 */	"# filler",
	/* 968 */	"# filler",
	/* 969 */	"# filler",
	/* 970 */	"# filler",
	/* 971 */	"# filler",
	/* 972 */	"# filler",
	/* 973 */	"# filler",
	/* 974 */	"# filler",
	/* 975 */	"# filler",
	/* 976 */	"# filler",
	/* 977 */	"# filler",
	/* 978 */	"# filler",
	/* 979 */	"# filler",
	/* 980 */	"# filler",
	/* 981 */	"# filler",
	/* 982 */	"# filler",
	/* 983 */	"# filler",
	/* 984 */	"# filler",
	/* 985 */	"# filler",
	/* 986 */	"# filler",
	/* 987 */	"# filler",
	/* 988 */	"# filler",
	/* 989 */	"# filler",
	/* 990 */	"# filler",
	/* 991 */	"# filler",
	/* 992 */	"# filler",
	/* 993 */	"# filler",
	/* 994 */	"# filler",
	/* 995 */	"# filler",
	/* 996 */	"# filler",
	/* 997 */	"# filler",
	/* 998 */	"# filler",
	/* 999 */	"# filler",
	/* 1000 */	"# filler",
	/* 1001 */	"# filler",
	/* 1002 */	"# filler",
	/* 1003 */	"# filler",
	/* 1004 */	"# filler",
	/* 1005 */	"# filler",
	/* 1006 */	"# filler",
	/* 1007 */	"# filler",
	/* 1008 */	"# filler",
	/* 1009 */	"# filler",
	/* 1010 */	"# filler",
	/* 1011 */	"# filler",
	/* 1012 */	"# filler",
	/* 1013 */	"# filler",
	/* 1014 */	"# filler",
	/* 1015 */	"# filler",
	/* 1016 */	"# filler",
	/* 1017 */	"# filler",
	/* 1018 */	"# filler",
	/* 1019 */	"# filler",
	/* 1020 */	"# filler",
	/* 1021 */	"# filler",
	/* 1022 */	"# filler",
	/* 1023 */	"# filler",
};


/* libc style syscall names */
const char *const altsyscallnames[] = {
	/*   0 */	NULL, /* syscall */
	/*   1 */	NULL, /* exit */
	/*   2 */	NULL, /* fork */
	/*   3 */	NULL, /* read */
	/*   4 */	NULL, /* write */
	/*   5 */	NULL, /* open */
	/*   6 */	NULL, /* close */
	/*   7 */	NULL, /* compat_50_wait4 */
	/*   8 */	NULL, /* compat_43_ocreat */
	/*   9 */	NULL, /* link */
	/*  10 */	NULL, /* unlink */
	/*  11 */	NULL, /* obsolete execv */
	/*  12 */	NULL, /* chdir */
	/*  13 */	NULL, /* fchdir */
	/*  14 */	NULL, /* compat_50_mknod */
	/*  15 */	NULL, /* chmod */
	/*  16 */	NULL, /* chown */
	/*  17 */	"obreak",
	/*  18 */	NULL, /* compat_20_getfsstat */
	/*  19 */	NULL, /* compat_43_olseek */
	/*  20 */	"getpid_with_ppid",
	/*  21 */	NULL, /* compat_40_mount */
	/*  22 */	NULL, /* unmount */
	/*  23 */	NULL, /* setuid */
	/*  24 */	"getuid_with_euid",
	/*  25 */	NULL, /* geteuid */
	/*  26 */	NULL, /* ptrace */
	/*  27 */	NULL, /* recvmsg */
	/*  28 */	NULL, /* sendmsg */
	/*  29 */	NULL, /* recvfrom */
	/*  30 */	NULL, /* accept */
	/*  31 */	NULL, /* getpeername */
	/*  32 */	NULL, /* getsockname */
	/*  33 */	NULL, /* access */
	/*  34 */	NULL, /* chflags */
	/*  35 */	NULL, /* fchflags */
	/*  36 */	NULL, /* sync */
	/*  37 */	NULL, /* kill */
	/*  38 */	NULL, /* compat_43_stat43 */
	/*  39 */	NULL, /* getppid */
	/*  40 */	NULL, /* compat_43_lstat43 */
	/*  41 */	NULL, /* dup */
	/*  42 */	NULL, /* pipe */
	/*  43 */	NULL, /* getegid */
	/*  44 */	NULL, /* profil */
	/*  45 */	NULL, /* ktrace */
	/*  46 */	NULL, /* compat_13_sigaction13 */
	/*  47 */	"getgid_with_egid",
	/*  48 */	NULL, /* compat_13_sigprocmask13 */
	/*  49 */	NULL, /* __getlogin */
	/*  50 */	NULL, /* __setlogin */
	/*  51 */	NULL, /* acct */
	/*  52 */	NULL, /* compat_13_sigpending13 */
	/*  53 */	NULL, /* compat_13_sigaltstack13 */
	/*  54 */	NULL, /* ioctl */
	/*  55 */	NULL, /* compat_12_oreboot */
	/*  56 */	NULL, /* revoke */
	/*  57 */	NULL, /* symlink */
	/*  58 */	NULL, /* readlink */
	/*  59 */	NULL, /* execve */
	/*  60 */	NULL, /* umask */
	/*  61 */	NULL, /* chroot */
	/*  62 */	NULL, /* compat_43_fstat43 */
	/*  63 */	NULL, /* compat_43_ogetkerninfo */
	/*  64 */	NULL, /* compat_43_ogetpagesize */
	/*  65 */	NULL, /* compat_12_msync */
	/*  66 */	NULL, /* vfork */
	/*  67 */	NULL, /* obsolete vread */
	/*  68 */	NULL, /* obsolete vwrite */
	/*  69 */	NULL, /* obsolete sbrk */
	/*  70 */	NULL, /* obsolete sstk */
	/*  71 */	NULL, /* compat_43_ommap */
	/*  72 */	"ovadvise",
	/*  73 */	NULL, /* munmap */
	/*  74 */	NULL, /* mprotect */
	/*  75 */	NULL, /* madvise */
	/*  76 */	NULL, /* obsolete vhangup */
	/*  77 */	NULL, /* obsolete vlimit */
	/*  78 */	NULL, /* mincore */
	/*  79 */	NULL, /* getgroups */
	/*  80 */	NULL, /* setgroups */
	/*  81 */	NULL, /* getpgrp */
	/*  82 */	NULL, /* setpgid */
	/*  83 */	NULL, /* compat_50_setitimer */
	/*  84 */	NULL, /* compat_43_owait */
	/*  85 */	NULL, /* compat_12_oswapon */
	/*  86 */	NULL, /* compat_50_getitimer */
	/*  87 */	NULL, /* compat_43_ogethostname */
	/*  88 */	NULL, /* compat_43_osethostname */
	/*  89 */	NULL, /* compat_43_ogetdtablesize */
	/*  90 */	NULL, /* dup2 */
	/*  91 */	NULL, /* getrandom */
	/*  92 */	NULL, /* fcntl */
	/*  93 */	NULL, /* compat_50_select */
	/*  94 */	NULL, /* unimplemented setdopt */
	/*  95 */	NULL, /* fsync */
	/*  96 */	NULL, /* setpriority */
	/*  97 */	NULL, /* compat_30_socket */
	/*  98 */	NULL, /* connect */
	/*  99 */	NULL, /* compat_43_oaccept */
	/* 100 */	NULL, /* getpriority */
	/* 101 */	NULL, /* compat_43_osend */
	/* 102 */	NULL, /* compat_43_orecv */
	/* 103 */	NULL, /* compat_13_sigreturn13 */
	/* 104 */	NULL, /* bind */
	/* 105 */	NULL, /* setsockopt */
	/* 106 */	NULL, /* listen */
	/* 107 */	NULL, /* obsolete vtimes */
	/* 108 */	NULL, /* compat_43_osigvec */
	/* 109 */	NULL, /* compat_43_osigblock */
	/* 110 */	NULL, /* compat_43_osigsetmask */
	/* 111 */	NULL, /* compat_13_sigsuspend13 */
	/* 112 */	NULL, /* compat_43_osigstack */
	/* 113 */	NULL, /* compat_43_orecvmsg */
	/* 114 */	NULL, /* compat_43_osendmsg */
	/* 115 */	NULL, /* obsolete vtrace */
	/* 116 */	NULL, /* compat_50_gettimeofday */
	/* 117 */	NULL, /* compat_50_getrusage */
	/* 118 */	NULL, /* getsockopt */
	/* 119 */	NULL, /* obsolete resuba */
	/* 120 */	NULL, /* readv */
	/* 121 */	NULL, /* writev */
	/* 122 */	NULL, /* compat_50_settimeofday */
	/* 123 */	NULL, /* fchown */
	/* 124 */	NULL, /* fchmod */
	/* 125 */	NULL, /* compat_43_orecvfrom */
	/* 126 */	NULL, /* setreuid */
	/* 127 */	NULL, /* setregid */
	/* 128 */	NULL, /* rename */
	/* 129 */	NULL, /* compat_43_otruncate */
	/* 130 */	NULL, /* compat_43_oftruncate */
	/* 131 */	NULL, /* flock */
	/* 132 */	NULL, /* mkfifo */
	/* 133 */	NULL, /* sendto */
	/* 134 */	NULL, /* shutdown */
	/* 135 */	NULL, /* socketpair */
	/* 136 */	NULL, /* mkdir */
	/* 137 */	NULL, /* rmdir */
	/* 138 */	NULL, /* compat_50_utimes */
	/* 139 */	NULL, /* obsolete 4.2 sigreturn */
	/* 140 */	NULL, /* compat_50_adjtime */
	/* 141 */	NULL, /* compat_43_ogetpeername */
	/* 142 */	NULL, /* compat_43_ogethostid */
	/* 143 */	NULL, /* compat_43_osethostid */
	/* 144 */	NULL, /* compat_43_ogetrlimit */
	/* 145 */	NULL, /* compat_43_osetrlimit */
	/* 146 */	NULL, /* compat_43_okillpg */
	/* 147 */	NULL, /* setsid */
	/* 148 */	NULL, /* compat_50_quotactl */
	/* 149 */	NULL, /* compat_43_oquota */
	/* 150 */	NULL, /* compat_43_ogetsockname */
	/* 151 */	NULL, /* unimplemented */
	/* 152 */	NULL, /* unimplemented */
	/* 153 */	NULL, /* unimplemented */
	/* 154 */	NULL, /* unimplemented */
	/* 155 */	NULL, /* nfssvc */
	/* 156 */	NULL, /* compat_43_ogetdirentries */
	/* 157 */	NULL, /* compat_20_statfs */
	/* 158 */	NULL, /* compat_20_fstatfs */
	/* 159 */	NULL, /* unimplemented */
	/* 160 */	NULL, /* unimplemented */
	/* 161 */	NULL, /* compat_30_getfh */
	/* 162 */	NULL, /* compat_09_ogetdomainname */
	/* 163 */	NULL, /* compat_09_osetdomainname */
	/* 164 */	NULL, /* compat_09_ouname */
	/* 165 */	NULL, /* sysarch */
	/* 166 */	NULL, /* __futex */
	/* 167 */	NULL, /* __futex_set_robust_list */
	/* 168 */	NULL, /* __futex_get_robust_list */
#if !defined(_LP64)
	/* 169 */	NULL, /* compat_10_osemsys */
#else
	/* 169 */	NULL, /* excluded 1.0 semsys */
#endif
#if !defined(_LP64)
	/* 170 */	NULL, /* compat_10_omsgsys */
#else
	/* 170 */	NULL, /* excluded 1.0 msgsys */
#endif
#if !defined(_LP64)
	/* 171 */	NULL, /* compat_10_oshmsys */
#else
	/* 171 */	NULL, /* excluded 1.0 shmsys */
#endif
	/* 172 */	NULL, /* unimplemented */
	/* 173 */	NULL, /* pread */
	/* 174 */	NULL, /* pwrite */
	/* 175 */	NULL, /* compat_30_ntp_gettime */
#if defined(NTP) || !defined(_KERNEL_OPT)
	/* 176 */	NULL, /* ntp_adjtime */
#else
	/* 176 */	NULL, /* excluded ntp_adjtime */
#endif
	/* 177 */	NULL, /* timerfd_create */
	/* 178 */	NULL, /* timerfd_settime */
	/* 179 */	NULL, /* timerfd_gettime */
	/* 180 */	NULL, /* unimplemented */
	/* 181 */	NULL, /* setgid */
	/* 182 */	NULL, /* setegid */
	/* 183 */	NULL, /* seteuid */
	/* 184 */	NULL, /* lfs_bmapv */
	/* 185 */	NULL, /* lfs_markv */
	/* 186 */	NULL, /* lfs_segclean */
	/* 187 */	NULL, /* compat_50_lfs_segwait */
	/* 188 */	NULL, /* compat_12_stat12 */
	/* 189 */	NULL, /* compat_12_fstat12 */
	/* 190 */	NULL, /* compat_12_lstat12 */
	/* 191 */	NULL, /* pathconf */
	/* 192 */	NULL, /* fpathconf */
	/* 193 */	NULL, /* getsockopt2 */
	/* 194 */	NULL, /* getrlimit */
	/* 195 */	NULL, /* setrlimit */
	/* 196 */	NULL, /* compat_12_getdirentries */
	/* 197 */	NULL, /* mmap */
	/* 198 */	NULL, /* __syscall */
	/* 199 */	NULL, /* lseek */
	/* 200 */	NULL, /* truncate */
	/* 201 */	NULL, /* ftruncate */
	/* 202 */	NULL, /* __sysctl */
	/* 203 */	NULL, /* mlock */
	/* 204 */	NULL, /* munlock */
	/* 205 */	NULL, /* undelete */
	/* 206 */	NULL, /* compat_50_futimes */
	/* 207 */	NULL, /* getpgid */
	/* 208 */	NULL, /* reboot */
	/* 209 */	NULL, /* poll */
	/* 210 */	NULL, /* afssys */
	/* 211 */	NULL, /* unimplemented */
	/* 212 */	NULL, /* unimplemented */
	/* 213 */	NULL, /* unimplemented */
	/* 214 */	NULL, /* unimplemented */
	/* 215 */	NULL, /* unimplemented */
	/* 216 */	NULL, /* unimplemented */
	/* 217 */	NULL, /* unimplemented */
	/* 218 */	NULL, /* unimplemented */
	/* 219 */	NULL, /* unimplemented */
	/* 220 */	NULL, /* compat_14___semctl */
	/* 221 */	NULL, /* semget */
	/* 222 */	NULL, /* semop */
	/* 223 */	NULL, /* semconfig */
	/* 224 */	NULL, /* compat_14_msgctl */
	/* 225 */	NULL, /* msgget */
	/* 226 */	NULL, /* msgsnd */
	/* 227 */	NULL, /* msgrcv */
	/* 228 */	NULL, /* shmat */
	/* 229 */	NULL, /* compat_14_shmctl */
	/* 230 */	NULL, /* shmdt */
	/* 231 */	NULL, /* shmget */
	/* 232 */	NULL, /* compat_50_clock_gettime */
	/* 233 */	NULL, /* compat_50_clock_settime */
	/* 234 */	NULL, /* compat_50_clock_getres */
	/* 235 */	NULL, /* timer_create */
	/* 236 */	NULL, /* timer_delete */
	/* 237 */	NULL, /* compat_50_timer_settime */
	/* 238 */	NULL, /* compat_50_timer_gettime */
	/* 239 */	NULL, /* timer_getoverrun */
	/* 240 */	NULL, /* compat_50_nanosleep */
	/* 241 */	NULL, /* fdatasync */
	/* 242 */	NULL, /* mlockall */
	/* 243 */	NULL, /* munlockall */
	/* 244 */	NULL, /* compat_50___sigtimedwait */
	/* 245 */	NULL, /* sigqueueinfo */
	/* 246 */	NULL, /* modctl */
	/* 247 */	NULL, /* _ksem_init */
	/* 248 */	NULL, /* _ksem_open */
	/* 249 */	NULL, /* _ksem_unlink */
	/* 250 */	NULL, /* _ksem_close */
	/* 251 */	NULL, /* _ksem_post */
	/* 252 */	NULL, /* _ksem_wait */
	/* 253 */	NULL, /* _ksem_trywait */
	/* 254 */	NULL, /* _ksem_getvalue */
	/* 255 */	NULL, /* _ksem_destroy */
	/* 256 */	NULL, /* _ksem_timedwait */
	/* 257 */	NULL, /* mq_open */
	/* 258 */	NULL, /* mq_close */
	/* 259 */	NULL, /* mq_unlink */
	/* 260 */	NULL, /* mq_getattr */
	/* 261 */	NULL, /* mq_setattr */
	/* 262 */	NULL, /* mq_notify */
	/* 263 */	NULL, /* mq_send */
	/* 264 */	NULL, /* mq_receive */
	/* 265 */	NULL, /* compat_50_mq_timedsend */
	/* 266 */	NULL, /* compat_50_mq_timedreceive */
	/* 267 */	NULL, /* eventfd */
	/* 268 */	NULL, /* unimplemented */
	/* 269 */	NULL, /* unimplemented */
	/* 270 */	NULL, /* __posix_rename */
	/* 271 */	NULL, /* swapctl */
	/* 272 */	NULL, /* compat_30_getdents */
	/* 273 */	NULL, /* minherit */
	/* 274 */	NULL, /* lchmod */
	/* 275 */	NULL, /* lchown */
	/* 276 */	NULL, /* compat_50_lutimes */
	/* 277 */	"msync",
	/* 278 */	NULL, /* compat_30___stat13 */
	/* 279 */	NULL, /* compat_30___fstat13 */
	/* 280 */	NULL, /* compat_30___lstat13 */
	/* 281 */	"sigaltstack",
	/* 282 */	"vfork",
	/* 283 */	NULL, /* __posix_chown */
	/* 284 */	NULL, /* __posix_fchown */
	/* 285 */	NULL, /* __posix_lchown */
	/* 286 */	NULL, /* getsid */
	/* 287 */	NULL, /* __clone */
	/* 288 */	NULL, /* fktrace */
	/* 289 */	NULL, /* preadv */
	/* 290 */	NULL, /* pwritev */
	/* 291 */	NULL, /* compat_16___sigaction14 */
	/* 292 */	"sigpending",
	/* 293 */	"sigprocmask",
	/* 294 */	"sigsuspend",
	/* 295 */	NULL, /* compat_16___sigreturn14 */
	/* 296 */	NULL, /* __getcwd */
	/* 297 */	NULL, /* fchroot */
	/* 298 */	NULL, /* compat_30_fhopen */
	/* 299 */	NULL, /* compat_30_fhstat */
	/* 300 */	NULL, /* compat_20_fhstatfs */
	/* 301 */	NULL, /* compat_50_____semctl13 */
	/* 302 */	NULL, /* compat_50___msgctl13 */
	/* 303 */	NULL, /* compat_50___shmctl13 */
	/* 304 */	NULL, /* lchflags */
	/* 305 */	NULL, /* issetugid */
	/* 306 */	NULL, /* utrace */
	/* 307 */	NULL, /* getcontext */
	/* 308 */	NULL, /* setcontext */
	/* 309 */	NULL, /* _lwp_create */
	/* 310 */	NULL, /* _lwp_exit */
	/* 311 */	NULL, /* _lwp_self */
	/* 312 */	NULL, /* _lwp_wait */
	/* 313 */	NULL, /* _lwp_suspend */
	/* 314 */	NULL, /* _lwp_continue */
	/* 315 */	NULL, /* _lwp_wakeup */
	/* 316 */	NULL, /* _lwp_getprivate */
	/* 317 */	NULL, /* _lwp_setprivate */
	/* 318 */	NULL, /* _lwp_kill */
	/* 319 */	NULL, /* _lwp_detach */
	/* 320 */	NULL, /* compat_50__lwp_park */
	/* 321 */	NULL, /* _lwp_unpark */
	/* 322 */	NULL, /* _lwp_unpark_all */
	/* 323 */	NULL, /* _lwp_setname */
	/* 324 */	NULL, /* _lwp_getname */
	/* 325 */	NULL, /* _lwp_ctl */
	/* 326 */	NULL, /* unimplemented */
	/* 327 */	NULL, /* unimplemented */
	/* 328 */	NULL, /* unimplemented */
	/* 329 */	NULL, /* unimplemented */
	/* 330 */	NULL, /* compat_60_sa_register */
	/* 331 */	NULL, /* compat_60_sa_stacks */
	/* 332 */	NULL, /* compat_60_sa_enable */
	/* 333 */	NULL, /* compat_60_sa_setconcurrency */
	/* 334 */	NULL, /* compat_60_sa_yield */
	/* 335 */	NULL, /* compat_60_sa_preempt */
	/* 336 */	NULL, /* obsolete sys_sa_unblockyield */
	/* 337 */	NULL, /* unimplemented */
	/* 338 */	NULL, /* unimplemented */
	/* 339 */	NULL, /* unimplemented */
	/* 340 */	NULL, /* __sigaction_sigtramp */
	/* 341 */	NULL, /* obsolete sys_pmc_get_info */
	/* 342 */	NULL, /* obsolete sys_pmc_control */
	/* 343 */	NULL, /* rasctl */
	/* 344 */	NULL, /* kqueue */
	/* 345 */	NULL, /* compat_50_kevent */
	/* 346 */	NULL, /* _sched_setparam */
	/* 347 */	NULL, /* _sched_getparam */
	/* 348 */	NULL, /* _sched_setaffinity */
	/* 349 */	NULL, /* _sched_getaffinity */
	/* 350 */	NULL, /* sched_yield */
	/* 351 */	NULL, /* _sched_protect */
	/* 352 */	NULL, /* unimplemented */
	/* 353 */	NULL, /* unimplemented */
	/* 354 */	NULL, /* fsync_range */
	/* 355 */	NULL, /* uuidgen */
	/* 356 */	NULL, /* compat_90_getvfsstat */
	/* 357 */	NULL, /* compat_90_statvfs1 */
	/* 358 */	NULL, /* compat_90_fstatvfs1 */
	/* 359 */	NULL, /* compat_30_fhstatvfs1 */
	/* 360 */	NULL, /* extattrctl */
	/* 361 */	NULL, /* extattr_set_file */
	/* 362 */	NULL, /* extattr_get_file */
	/* 363 */	NULL, /* extattr_delete_file */
	/* 364 */	NULL, /* extattr_set_fd */
	/* 365 */	NULL, /* extattr_get_fd */
	/* 366 */	NULL, /* extattr_delete_fd */
	/* 367 */	NULL, /* extattr_set_link */
	/* 368 */	NULL, /* extattr_get_link */
	/* 369 */	NULL, /* extattr_delete_link */
	/* 370 */	NULL, /* extattr_list_fd */
	/* 371 */	NULL, /* extattr_list_file */
	/* 372 */	NULL, /* extattr_list_link */
	/* 373 */	NULL, /* compat_50_pselect */
	/* 374 */	NULL, /* compat_50_pollts */
	/* 375 */	NULL, /* setxattr */
	/* 376 */	NULL, /* lsetxattr */
	/* 377 */	NULL, /* fsetxattr */
	/* 378 */	NULL, /* getxattr */
	/* 379 */	NULL, /* lgetxattr */
	/* 380 */	NULL, /* fgetxattr */
	/* 381 */	NULL, /* listxattr */
	/* 382 */	NULL, /* llistxattr */
	/* 383 */	NULL, /* flistxattr */
	/* 384 */	NULL, /* removexattr */
	/* 385 */	NULL, /* lremovexattr */
	/* 386 */	NULL, /* fremovexattr */
	/* 387 */	NULL, /* compat_50___stat30 */
	/* 388 */	NULL, /* compat_50___fstat30 */
	/* 389 */	NULL, /* compat_50___lstat30 */
	/* 390 */	"getdents",
	/* 391 */	NULL, /* ignored old posix_fadvise */
	/* 392 */	NULL, /* compat_30___fhstat30 */
	/* 393 */	NULL, /* compat_50___ntp_gettime30 */
	/* 394 */	"socket",
	/* 395 */	"getfh",
	/* 396 */	"fhopen",
	/* 397 */	NULL, /* compat_90_fhstatvfs1 */
	/* 398 */	NULL, /* compat_50___fhstat40 */
	/* 399 */	NULL, /* aio_cancel */
	/* 400 */	NULL, /* aio_error */
	/* 401 */	NULL, /* aio_fsync */
	/* 402 */	NULL, /* aio_read */
	/* 403 */	NULL, /* aio_return */
	/* 404 */	NULL, /* compat_50_aio_suspend */
	/* 405 */	NULL, /* aio_write */
	/* 406 */	NULL, /* lio_listio */
	/* 407 */	NULL, /* unimplemented */
	/* 408 */	NULL, /* unimplemented */
	/* 409 */	NULL, /* unimplemented */
	/* 410 */	"mount",
	/* 411 */	NULL, /* mremap */
	/* 412 */	NULL, /* pset_create */
	/* 413 */	NULL, /* pset_destroy */
	/* 414 */	NULL, /* pset_assign */
	/* 415 */	NULL, /* _pset_bind */
	/* 416 */	"posix_fadvise",
	/* 417 */	"select",
	/* 418 */	"gettimeofday",
	/* 419 */	"settimeofday",
	/* 420 */	"utimes",
	/* 421 */	"adjtime",
	/* 422 */	"lfs_segwait",
	/* 423 */	"futimes",
	/* 424 */	"lutimes",
	/* 425 */	"setitimer",
	/* 426 */	"getitimer",
	/* 427 */	"clock_gettime",
	/* 428 */	"clock_settime",
	/* 429 */	"clock_getres",
	/* 430 */	"nanosleep",
	/* 431 */	"__sigtimedwait",
	/* 432 */	"mq_timedsend",
	/* 433 */	"mq_timedreceive",
	/* 434 */	NULL, /* compat_60__lwp_park */
	/* 435 */	"kevent",
	/* 436 */	"pselect",
	/* 437 */	"pollts",
	/* 438 */	"aio_suspend",
	/* 439 */	"stat",
	/* 440 */	"fstat",
	/* 441 */	"lstat",
	/* 442 */	"__semctl",
	/* 443 */	"shmctl",
	/* 444 */	"msgctl",
	/* 445 */	"getrusage",
	/* 446 */	"timer_settime",
	/* 447 */	"timer_gettime",
#if defined(NTP) || !defined(_KERNEL_OPT)
	/* 448 */	"ntp_gettime",
#else
	/* 448 */	NULL, /* excluded ___ntp_gettime50 */
#endif
	/* 449 */	"wait4",
	/* 450 */	"mknod",
	/* 451 */	"fhstat",
	/* 452 */	NULL, /* obsolete 5.99 quotactl */
	/* 453 */	NULL, /* pipe2 */
	/* 454 */	NULL, /* dup3 */
	/* 455 */	NULL, /* kqueue1 */
	/* 456 */	NULL, /* paccept */
	/* 457 */	NULL, /* linkat */
	/* 458 */	NULL, /* renameat */
	/* 459 */	NULL, /* mkfifoat */
	/* 460 */	NULL, /* mknodat */
	/* 461 */	NULL, /* mkdirat */
	/* 462 */	NULL, /* faccessat */
	/* 463 */	NULL, /* fchmodat */
	/* 464 */	NULL, /* fchownat */
	/* 465 */	NULL, /* fexecve */
	/* 466 */	NULL, /* fstatat */
	/* 467 */	NULL, /* utimensat */
	/* 468 */	NULL, /* openat */
	/* 469 */	NULL, /* readlinkat */
	/* 470 */	NULL, /* symlinkat */
	/* 471 */	NULL, /* unlinkat */
	/* 472 */	NULL, /* futimens */
	/* 473 */	NULL, /* __quotactl */
	/* 474 */	NULL, /* posix_spawn */
	/* 475 */	NULL, /* recvmmsg */
	/* 476 */	NULL, /* sendmmsg */
	/* 477 */	NULL, /* clock_nanosleep */
	/* 478 */	"_lwp_park",
	/* 479 */	NULL, /* posix_fallocate */
	/* 480 */	NULL, /* fdiscard */
	/* 481 */	NULL, /* wait6 */
	/* 482 */	NULL, /* clock_getcpuclockid2 */
	/* 483 */	"getvfsstat",
	/* 484 */	"statvfs1",
	/* 485 */	"fstatvfs1",
	/* 486 */	"fhstatvfs1",
	/* 487 */	NULL, /* __acl_get_link */
	/* 488 */	NULL, /* __acl_set_link */
	/* 489 */	NULL, /* __acl_delete_link */
	/* 490 */	NULL, /* __acl_aclcheck_link */
	/* 491 */	NULL, /* __acl_get_file */
	/* 492 */	NULL, /* __acl_set_file */
	/* 493 */	NULL, /* __acl_get_fd */
	/* 494 */	NULL, /* __acl_set_fd */
	/* 495 */	NULL, /* __acl_delete_file */
	/* 496 */	NULL, /* __acl_delete_fd */
	/* 497 */	NULL, /* __acl_aclcheck_file */
	/* 498 */	NULL, /* __acl_aclcheck_fd */
	/* 499 */	NULL, /* lpathconf */
	/* 500 */	NULL, /* _create_port */
	/* 501 */	NULL, /* _close_port */
	/* 502 */	NULL, /* _delete_port */
	/* 503 */	NULL, /* _find_port */
	/* 504 */	NULL, /* _get_port_info */
	/* 505 */	NULL, /* _get_next_port_info */
	/* 506 */	NULL, /* _port_buffer_size */
	/* 507 */	NULL, /* _port_buffer_size_etc */
	/* 508 */	NULL, /* _port_count */
	/* 509 */	NULL, /* _read_port */
	/* 510 */	NULL, /* _read_port_etc */
	/* 511 */	NULL, /* _set_port_owner */
	/* 512 */	NULL, /* _write_port */
	/* 513 */	NULL, /* _write_port_etc */
	/* 514 */	NULL, /* _create_sem */
	/* 515 */	NULL, /* _delete_sem */
	/* 516 */	NULL, /* _acquire_sem */
	/* 517 */	NULL, /* _acquire_sem_etc */
	/* 518 */	NULL, /* _release_sem */
	/* 519 */	NULL, /* _release_sem_etc */
	/* 520 */	NULL, /* _get_sem_count */
	/* 521 */	NULL, /* _set_sem_owner */
	/* 522 */	NULL, /* _get_sem_info */
	/* 523 */	NULL, /* _get_next_sem_info */
	/* 524 */	NULL, /* _create_area */
	/* 525 */	NULL, /* _clone_area */
	/* 526 */	NULL, /* _find_area */
	/* 527 */	NULL, /* _area_for */
	/* 528 */	NULL, /* _delete_area */
	/* 529 */	NULL, /* _resize_area */
	/* 530 */	NULL, /* _set_area_protection */
	/* 531 */	NULL, /* _get_area_info */
	/* 532 */	NULL, /* _get_next_area_info */
	/* 533 */	NULL, /* filler */
	/* 534 */	NULL, /* filler */
	/* 535 */	NULL, /* filler */
	/* 536 */	NULL, /* filler */
	/* 537 */	NULL, /* filler */
	/* 538 */	NULL, /* filler */
	/* 539 */	NULL, /* filler */
	/* 540 */	NULL, /* filler */
	/* 541 */	NULL, /* filler */
	/* 542 */	NULL, /* filler */
	/* 543 */	NULL, /* filler */
	/* 544 */	NULL, /* filler */
	/* 545 */	NULL, /* filler */
	/* 546 */	NULL, /* filler */
	/* 547 */	NULL, /* filler */
	/* 548 */	NULL, /* filler */
	/* 549 */	NULL, /* filler */
	/* 550 */	NULL, /* filler */
	/* 551 */	NULL, /* filler */
	/* 552 */	NULL, /* filler */
	/* 553 */	NULL, /* filler */
	/* 554 */	NULL, /* filler */
	/* 555 */	NULL, /* filler */
	/* 556 */	NULL, /* filler */
	/* 557 */	NULL, /* filler */
	/* 558 */	NULL, /* filler */
	/* 559 */	NULL, /* filler */
	/* 560 */	NULL, /* filler */
	/* 561 */	NULL, /* filler */
	/* 562 */	NULL, /* filler */
	/* 563 */	NULL, /* filler */
	/* 564 */	NULL, /* filler */
	/* 565 */	NULL, /* filler */
	/* 566 */	NULL, /* filler */
	/* 567 */	NULL, /* filler */
	/* 568 */	NULL, /* filler */
	/* 569 */	NULL, /* filler */
	/* 570 */	NULL, /* filler */
	/* 571 */	NULL, /* filler */
	/* 572 */	NULL, /* filler */
	/* 573 */	NULL, /* filler */
	/* 574 */	NULL, /* filler */
	/* 575 */	NULL, /* filler */
	/* 576 */	NULL, /* filler */
	/* 577 */	NULL, /* filler */
	/* 578 */	NULL, /* filler */
	/* 579 */	NULL, /* filler */
	/* 580 */	NULL, /* filler */
	/* 581 */	NULL, /* filler */
	/* 582 */	NULL, /* filler */
	/* 583 */	NULL, /* filler */
	/* 584 */	NULL, /* filler */
	/* 585 */	NULL, /* filler */
	/* 586 */	NULL, /* filler */
	/* 587 */	NULL, /* filler */
	/* 588 */	NULL, /* filler */
	/* 589 */	NULL, /* filler */
	/* 590 */	NULL, /* filler */
	/* 591 */	NULL, /* filler */
	/* 592 */	NULL, /* filler */
	/* 593 */	NULL, /* filler */
	/* 594 */	NULL, /* filler */
	/* 595 */	NULL, /* filler */
	/* 596 */	NULL, /* filler */
	/* 597 */	NULL, /* filler */
	/* 598 */	NULL, /* filler */
	/* 599 */	NULL, /* filler */
	/* 600 */	NULL, /* filler */
	/* 601 */	NULL, /* filler */
	/* 602 */	NULL, /* filler */
	/* 603 */	NULL, /* filler */
	/* 604 */	NULL, /* filler */
	/* 605 */	NULL, /* filler */
	/* 606 */	NULL, /* filler */
	/* 607 */	NULL, /* filler */
	/* 608 */	NULL, /* filler */
	/* 609 */	NULL, /* filler */
	/* 610 */	NULL, /* filler */
	/* 611 */	NULL, /* filler */
	/* 612 */	NULL, /* filler */
	/* 613 */	NULL, /* filler */
	/* 614 */	NULL, /* filler */
	/* 615 */	NULL, /* filler */
	/* 616 */	NULL, /* filler */
	/* 617 */	NULL, /* filler */
	/* 618 */	NULL, /* filler */
	/* 619 */	NULL, /* filler */
	/* 620 */	NULL, /* filler */
	/* 621 */	NULL, /* filler */
	/* 622 */	NULL, /* filler */
	/* 623 */	NULL, /* filler */
	/* 624 */	NULL, /* filler */
	/* 625 */	NULL, /* filler */
	/* 626 */	NULL, /* filler */
	/* 627 */	NULL, /* filler */
	/* 628 */	NULL, /* filler */
	/* 629 */	NULL, /* filler */
	/* 630 */	NULL, /* filler */
	/* 631 */	NULL, /* filler */
	/* 632 */	NULL, /* filler */
	/* 633 */	NULL, /* filler */
	/* 634 */	NULL, /* filler */
	/* 635 */	NULL, /* filler */
	/* 636 */	NULL, /* filler */
	/* 637 */	NULL, /* filler */
	/* 638 */	NULL, /* filler */
	/* 639 */	NULL, /* filler */
	/* 640 */	NULL, /* filler */
	/* 641 */	NULL, /* filler */
	/* 642 */	NULL, /* filler */
	/* 643 */	NULL, /* filler */
	/* 644 */	NULL, /* filler */
	/* 645 */	NULL, /* filler */
	/* 646 */	NULL, /* filler */
	/* 647 */	NULL, /* filler */
	/* 648 */	NULL, /* filler */
	/* 649 */	NULL, /* filler */
	/* 650 */	NULL, /* filler */
	/* 651 */	NULL, /* filler */
	/* 652 */	NULL, /* filler */
	/* 653 */	NULL, /* filler */
	/* 654 */	NULL, /* filler */
	/* 655 */	NULL, /* filler */
	/* 656 */	NULL, /* filler */
	/* 657 */	NULL, /* filler */
	/* 658 */	NULL, /* filler */
	/* 659 */	NULL, /* filler */
	/* 660 */	NULL, /* filler */
	/* 661 */	NULL, /* filler */
	/* 662 */	NULL, /* filler */
	/* 663 */	NULL, /* filler */
	/* 664 */	NULL, /* filler */
	/* 665 */	NULL, /* filler */
	/* 666 */	NULL, /* filler */
	/* 667 */	NULL, /* filler */
	/* 668 */	NULL, /* filler */
	/* 669 */	NULL, /* filler */
	/* 670 */	NULL, /* filler */
	/* 671 */	NULL, /* filler */
	/* 672 */	NULL, /* filler */
	/* 673 */	NULL, /* filler */
	/* 674 */	NULL, /* filler */
	/* 675 */	NULL, /* filler */
	/* 676 */	NULL, /* filler */
	/* 677 */	NULL, /* filler */
	/* 678 */	NULL, /* filler */
	/* 679 */	NULL, /* filler */
	/* 680 */	NULL, /* filler */
	/* 681 */	NULL, /* filler */
	/* 682 */	NULL, /* filler */
	/* 683 */	NULL, /* filler */
	/* 684 */	NULL, /* filler */
	/* 685 */	NULL, /* filler */
	/* 686 */	NULL, /* filler */
	/* 687 */	NULL, /* filler */
	/* 688 */	NULL, /* filler */
	/* 689 */	NULL, /* filler */
	/* 690 */	NULL, /* filler */
	/* 691 */	NULL, /* filler */
	/* 692 */	NULL, /* filler */
	/* 693 */	NULL, /* filler */
	/* 694 */	NULL, /* filler */
	/* 695 */	NULL, /* filler */
	/* 696 */	NULL, /* filler */
	/* 697 */	NULL, /* filler */
	/* 698 */	NULL, /* filler */
	/* 699 */	NULL, /* filler */
	/* 700 */	NULL, /* filler */
	/* 701 */	NULL, /* filler */
	/* 702 */	NULL, /* filler */
	/* 703 */	NULL, /* filler */
	/* 704 */	NULL, /* filler */
	/* 705 */	NULL, /* filler */
	/* 706 */	NULL, /* filler */
	/* 707 */	NULL, /* filler */
	/* 708 */	NULL, /* filler */
	/* 709 */	NULL, /* filler */
	/* 710 */	NULL, /* filler */
	/* 711 */	NULL, /* filler */
	/* 712 */	NULL, /* filler */
	/* 713 */	NULL, /* filler */
	/* 714 */	NULL, /* filler */
	/* 715 */	NULL, /* filler */
	/* 716 */	NULL, /* filler */
	/* 717 */	NULL, /* filler */
	/* 718 */	NULL, /* filler */
	/* 719 */	NULL, /* filler */
	/* 720 */	NULL, /* filler */
	/* 721 */	NULL, /* filler */
	/* 722 */	NULL, /* filler */
	/* 723 */	NULL, /* filler */
	/* 724 */	NULL, /* filler */
	/* 725 */	NULL, /* filler */
	/* 726 */	NULL, /* filler */
	/* 727 */	NULL, /* filler */
	/* 728 */	NULL, /* filler */
	/* 729 */	NULL, /* filler */
	/* 730 */	NULL, /* filler */
	/* 731 */	NULL, /* filler */
	/* 732 */	NULL, /* filler */
	/* 733 */	NULL, /* filler */
	/* 734 */	NULL, /* filler */
	/* 735 */	NULL, /* filler */
	/* 736 */	NULL, /* filler */
	/* 737 */	NULL, /* filler */
	/* 738 */	NULL, /* filler */
	/* 739 */	NULL, /* filler */
	/* 740 */	NULL, /* filler */
	/* 741 */	NULL, /* filler */
	/* 742 */	NULL, /* filler */
	/* 743 */	NULL, /* filler */
	/* 744 */	NULL, /* filler */
	/* 745 */	NULL, /* filler */
	/* 746 */	NULL, /* filler */
	/* 747 */	NULL, /* filler */
	/* 748 */	NULL, /* filler */
	/* 749 */	NULL, /* filler */
	/* 750 */	NULL, /* filler */
	/* 751 */	NULL, /* filler */
	/* 752 */	NULL, /* filler */
	/* 753 */	NULL, /* filler */
	/* 754 */	NULL, /* filler */
	/* 755 */	NULL, /* filler */
	/* 756 */	NULL, /* filler */
	/* 757 */	NULL, /* filler */
	/* 758 */	NULL, /* filler */
	/* 759 */	NULL, /* filler */
	/* 760 */	NULL, /* filler */
	/* 761 */	NULL, /* filler */
	/* 762 */	NULL, /* filler */
	/* 763 */	NULL, /* filler */
	/* 764 */	NULL, /* filler */
	/* 765 */	NULL, /* filler */
	/* 766 */	NULL, /* filler */
	/* 767 */	NULL, /* filler */
	/* 768 */	NULL, /* filler */
	/* 769 */	NULL, /* filler */
	/* 770 */	NULL, /* filler */
	/* 771 */	NULL, /* filler */
	/* 772 */	NULL, /* filler */
	/* 773 */	NULL, /* filler */
	/* 774 */	NULL, /* filler */
	/* 775 */	NULL, /* filler */
	/* 776 */	NULL, /* filler */
	/* 777 */	NULL, /* filler */
	/* 778 */	NULL, /* filler */
	/* 779 */	NULL, /* filler */
	/* 780 */	NULL, /* filler */
	/* 781 */	NULL, /* filler */
	/* 782 */	NULL, /* filler */
	/* 783 */	NULL, /* filler */
	/* 784 */	NULL, /* filler */
	/* 785 */	NULL, /* filler */
	/* 786 */	NULL, /* filler */
	/* 787 */	NULL, /* filler */
	/* 788 */	NULL, /* filler */
	/* 789 */	NULL, /* filler */
	/* 790 */	NULL, /* filler */
	/* 791 */	NULL, /* filler */
	/* 792 */	NULL, /* filler */
	/* 793 */	NULL, /* filler */
	/* 794 */	NULL, /* filler */
	/* 795 */	NULL, /* filler */
	/* 796 */	NULL, /* filler */
	/* 797 */	NULL, /* filler */
	/* 798 */	NULL, /* filler */
	/* 799 */	NULL, /* filler */
	/* 800 */	NULL, /* filler */
	/* 801 */	NULL, /* filler */
	/* 802 */	NULL, /* filler */
	/* 803 */	NULL, /* filler */
	/* 804 */	NULL, /* filler */
	/* 805 */	NULL, /* filler */
	/* 806 */	NULL, /* filler */
	/* 807 */	NULL, /* filler */
	/* 808 */	NULL, /* filler */
	/* 809 */	NULL, /* filler */
	/* 810 */	NULL, /* filler */
	/* 811 */	NULL, /* filler */
	/* 812 */	NULL, /* filler */
	/* 813 */	NULL, /* filler */
	/* 814 */	NULL, /* filler */
	/* 815 */	NULL, /* filler */
	/* 816 */	NULL, /* filler */
	/* 817 */	NULL, /* filler */
	/* 818 */	NULL, /* filler */
	/* 819 */	NULL, /* filler */
	/* 820 */	NULL, /* filler */
	/* 821 */	NULL, /* filler */
	/* 822 */	NULL, /* filler */
	/* 823 */	NULL, /* filler */
	/* 824 */	NULL, /* filler */
	/* 825 */	NULL, /* filler */
	/* 826 */	NULL, /* filler */
	/* 827 */	NULL, /* filler */
	/* 828 */	NULL, /* filler */
	/* 829 */	NULL, /* filler */
	/* 830 */	NULL, /* filler */
	/* 831 */	NULL, /* filler */
	/* 832 */	NULL, /* filler */
	/* 833 */	NULL, /* filler */
	/* 834 */	NULL, /* filler */
	/* 835 */	NULL, /* filler */
	/* 836 */	NULL, /* filler */
	/* 837 */	NULL, /* filler */
	/* 838 */	NULL, /* filler */
	/* 839 */	NULL, /* filler */
	/* 840 */	NULL, /* filler */
	/* 841 */	NULL, /* filler */
	/* 842 */	NULL, /* filler */
	/* 843 */	NULL, /* filler */
	/* 844 */	NULL, /* filler */
	/* 845 */	NULL, /* filler */
	/* 846 */	NULL, /* filler */
	/* 847 */	NULL, /* filler */
	/* 848 */	NULL, /* filler */
	/* 849 */	NULL, /* filler */
	/* 850 */	NULL, /* filler */
	/* 851 */	NULL, /* filler */
	/* 852 */	NULL, /* filler */
	/* 853 */	NULL, /* filler */
	/* 854 */	NULL, /* filler */
	/* 855 */	NULL, /* filler */
	/* 856 */	NULL, /* filler */
	/* 857 */	NULL, /* filler */
	/* 858 */	NULL, /* filler */
	/* 859 */	NULL, /* filler */
	/* 860 */	NULL, /* filler */
	/* 861 */	NULL, /* filler */
	/* 862 */	NULL, /* filler */
	/* 863 */	NULL, /* filler */
	/* 864 */	NULL, /* filler */
	/* 865 */	NULL, /* filler */
	/* 866 */	NULL, /* filler */
	/* 867 */	NULL, /* filler */
	/* 868 */	NULL, /* filler */
	/* 869 */	NULL, /* filler */
	/* 870 */	NULL, /* filler */
	/* 871 */	NULL, /* filler */
	/* 872 */	NULL, /* filler */
	/* 873 */	NULL, /* filler */
	/* 874 */	NULL, /* filler */
	/* 875 */	NULL, /* filler */
	/* 876 */	NULL, /* filler */
	/* 877 */	NULL, /* filler */
	/* 878 */	NULL, /* filler */
	/* 879 */	NULL, /* filler */
	/* 880 */	NULL, /* filler */
	/* 881 */	NULL, /* filler */
	/* 882 */	NULL, /* filler */
	/* 883 */	NULL, /* filler */
	/* 884 */	NULL, /* filler */
	/* 885 */	NULL, /* filler */
	/* 886 */	NULL, /* filler */
	/* 887 */	NULL, /* filler */
	/* 888 */	NULL, /* filler */
	/* 889 */	NULL, /* filler */
	/* 890 */	NULL, /* filler */
	/* 891 */	NULL, /* filler */
	/* 892 */	NULL, /* filler */
	/* 893 */	NULL, /* filler */
	/* 894 */	NULL, /* filler */
	/* 895 */	NULL, /* filler */
	/* 896 */	NULL, /* filler */
	/* 897 */	NULL, /* filler */
	/* 898 */	NULL, /* filler */
	/* 899 */	NULL, /* filler */
	/* 900 */	NULL, /* filler */
	/* 901 */	NULL, /* filler */
	/* 902 */	NULL, /* filler */
	/* 903 */	NULL, /* filler */
	/* 904 */	NULL, /* filler */
	/* 905 */	NULL, /* filler */
	/* 906 */	NULL, /* filler */
	/* 907 */	NULL, /* filler */
	/* 908 */	NULL, /* filler */
	/* 909 */	NULL, /* filler */
	/* 910 */	NULL, /* filler */
	/* 911 */	NULL, /* filler */
	/* 912 */	NULL, /* filler */
	/* 913 */	NULL, /* filler */
	/* 914 */	NULL, /* filler */
	/* 915 */	NULL, /* filler */
	/* 916 */	NULL, /* filler */
	/* 917 */	NULL, /* filler */
	/* 918 */	NULL, /* filler */
	/* 919 */	NULL, /* filler */
	/* 920 */	NULL, /* filler */
	/* 921 */	NULL, /* filler */
	/* 922 */	NULL, /* filler */
	/* 923 */	NULL, /* filler */
	/* 924 */	NULL, /* filler */
	/* 925 */	NULL, /* filler */
	/* 926 */	NULL, /* filler */
	/* 927 */	NULL, /* filler */
	/* 928 */	NULL, /* filler */
	/* 929 */	NULL, /* filler */
	/* 930 */	NULL, /* filler */
	/* 931 */	NULL, /* filler */
	/* 932 */	NULL, /* filler */
	/* 933 */	NULL, /* filler */
	/* 934 */	NULL, /* filler */
	/* 935 */	NULL, /* filler */
	/* 936 */	NULL, /* filler */
	/* 937 */	NULL, /* filler */
	/* 938 */	NULL, /* filler */
	/* 939 */	NULL, /* filler */
	/* 940 */	NULL, /* filler */
	/* 941 */	NULL, /* filler */
	/* 942 */	NULL, /* filler */
	/* 943 */	NULL, /* filler */
	/* 944 */	NULL, /* filler */
	/* 945 */	NULL, /* filler */
	/* 946 */	NULL, /* filler */
	/* 947 */	NULL, /* filler */
	/* 948 */	NULL, /* filler */
	/* 949 */	NULL, /* filler */
	/* 950 */	NULL, /* filler */
	/* 951 */	NULL, /* filler */
	/* 952 */	NULL, /* filler */
	/* 953 */	NULL, /* filler */
	/* 954 */	NULL, /* filler */
	/* 955 */	NULL, /* filler */
	/* 956 */	NULL, /* filler */
	/* 957 */	NULL, /* filler */
	/* 958 */	NULL, /* filler */
	/* 959 */	NULL, /* filler */
	/* 960 */	NULL, /* filler */
	/* 961 */	NULL, /* filler */
	/* 962 */	NULL, /* filler */
	/* 963 */	NULL, /* filler */
	/* 964 */	NULL, /* filler */
	/* 965 */	NULL, /* filler */
	/* 966 */	NULL, /* filler */
	/* 967 */	NULL, /* filler */
	/* 968 */	NULL, /* filler */
	/* 969 */	NULL, /* filler */
	/* 970 */	NULL, /* filler */
	/* 971 */	NULL, /* filler */
	/* 972 */	NULL, /* filler */
	/* 973 */	NULL, /* filler */
	/* 974 */	NULL, /* filler */
	/* 975 */	NULL, /* filler */
	/* 976 */	NULL, /* filler */
	/* 977 */	NULL, /* filler */
	/* 978 */	NULL, /* filler */
	/* 979 */	NULL, /* filler */
	/* 980 */	NULL, /* filler */
	/* 981 */	NULL, /* filler */
	/* 982 */	NULL, /* filler */
	/* 983 */	NULL, /* filler */
	/* 984 */	NULL, /* filler */
	/* 985 */	NULL, /* filler */
	/* 986 */	NULL, /* filler */
	/* 987 */	NULL, /* filler */
	/* 988 */	NULL, /* filler */
	/* 989 */	NULL, /* filler */
	/* 990 */	NULL, /* filler */
	/* 991 */	NULL, /* filler */
	/* 992 */	NULL, /* filler */
	/* 993 */	NULL, /* filler */
	/* 994 */	NULL, /* filler */
	/* 995 */	NULL, /* filler */
	/* 996 */	NULL, /* filler */
	/* 997 */	NULL, /* filler */
	/* 998 */	NULL, /* filler */
	/* 999 */	NULL, /* filler */
	/* 1000 */	NULL, /* filler */
	/* 1001 */	NULL, /* filler */
	/* 1002 */	NULL, /* filler */
	/* 1003 */	NULL, /* filler */
	/* 1004 */	NULL, /* filler */
	/* 1005 */	NULL, /* filler */
	/* 1006 */	NULL, /* filler */
	/* 1007 */	NULL, /* filler */
	/* 1008 */	NULL, /* filler */
	/* 1009 */	NULL, /* filler */
	/* 1010 */	NULL, /* filler */
	/* 1011 */	NULL, /* filler */
	/* 1012 */	NULL, /* filler */
	/* 1013 */	NULL, /* filler */
	/* 1014 */	NULL, /* filler */
	/* 1015 */	NULL, /* filler */
	/* 1016 */	NULL, /* filler */
	/* 1017 */	NULL, /* filler */
	/* 1018 */	NULL, /* filler */
	/* 1019 */	NULL, /* filler */
	/* 1020 */	NULL, /* filler */
	/* 1021 */	NULL, /* filler */
	/* 1022 */	NULL, /* filler */
	/* 1023 */	NULL, /* filler */
};
